config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "dashboards#overview", as: "overview"
  get "signs/requests", to: "signs#requests", as: "requests"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :signs
  resources :bookmarks
  resources :categories, only: [ :index, :show ]
  # resources :comments, only: [ :new, :create ] - should be nested inside :signs
  # resources :comments, only: [ :edit, :update, :destroy ]
  # resources :bookmarks, only: [ :index, :destroy ]
  # resources :lists do
  #   resources :bookmarks, only: [ :new, :create ]
  # end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p class="footer__text text-para--medium">Made with ❤️</p>
</footer>

app/views/shared/_form.html.erb
<div class="container py-5 form-adjust">
  <div class="row form-bg">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-4 shadow">
        <h3 class="font-delta">What should your new Sign be like?</h3>
        <%= simple_form_for(@sign) do |f| %>
          <%= f.input :language, collection: ["german", "english", "french", "swedish", "albanian", "bulgarian"]  %>
          <%= f.input :title, placeholder: 'Your Sign - Camel' %>
          <%= f.input :description, placeholder: 'What is your Sign all about?' %>
          <%= f.association :category %>
          <%= f.input :video, label: "Choose the sassy video for your sign"  %>
          <% if f.object.new_record? %>
            <%= f.submit "Create Sign", class: "btn create_video_button", id:"start" %>
          <% else %>
            <%= f.submit "Edit Sign", class: "btn create_video_button", id:"save" %>
          <% end %>
          <%= link_to "Cancel", :back, {:class=>"form--link"} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_home_nav.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top sticky">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "signup_logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="<%= is_active?(root_path)%>">
          <%= link_to "Home", root_path  %>
            <%# <button class="btn-link focus-tab", id="home-tab", onclick="updateFocus(this)">HOME</button> %>
        </li>
        <li class="<%= is_active?(overview_path)%>">
         <%= link_to "Dashboard", overview_path  %>
          <%# <%= link_to "dashboard" do %>
            <%# <button class="btn-link", id="dashboard-tab", onclick="updateFocus(this)">DASHBOARD</button> %>
          <%# <% end %>
        </li>
        <li class="<%= is_active?(bookmarks_path)%>">
         <%= link_to "Favorites", bookmarks_path  %>
          <%# <%= link_to root_path do %>
            <%# <button class="btn-link", id="lists-tab", onclick="updateFocus(this)">MY LISTS</button> %>
          <%# <% end %>
        </li>
        <li class="<%= is_active?(new_sign_path)%>">
        <%= link_to "Create", new_sign_path  %>
          <%# <%= link_to root_path do %>
            <%# <button class="btn-link", id="favorites-tab", onclick="updateFocus(this)">MY FAVORITES</button> %>
          <%# <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user-icon-normal.png", class: "avatar-bordered dropdown-toggle user-avatar ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "New Sign", new_sign_path, class: "dropdown-item" %>
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%# <a class="dropdown-item" data-method="delete" href="/users/sign_out" rel="nofollow">Log out</a> %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top sticky">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "signup-logo.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <%# <li>
          <%# <%= link_to root_path do %>
            <%# <button class="btn-link focus-tab", id="home-tab", onclick="updateFocus(this)">HOME</button> %>
          <%# <% end %>
        <%# </li>
        <li> %>
          <%# <%= link_to overview_path do %>
            <%# <button class="btn-link", id="dashboard-tab", onclick="updateFocus(this)">DASHBOARD</button> %>
          <%# <% end %>
        <%# </li>
        <li> %>
          <%# <%= link_to root_path do %>
            <%# <button class="btn-link", id="lists-tab", onclick="updateFocus(this)">LISTS</button> %>
          <%# <% end %>
        <%# </li>
        <li> %>
          <%# <%= link_to bookmarks_path do %>
            <%# <button class="btn-link", id="favorites-tab", onclick="updateFocus(this)">FAVORITES</button> %>

          <%# <% end %>
        <%# </li>
        <li> %>
          <%# <%= link_to categories_path do %>
            <%# <button class="btn-link", id="categories-tab", onclick="updateFocus(this)">CATEGORIES</button> %>
          <%# <% end %>
        <%# </li> %>
        <li class="<%= is_active?(root_path)%>">
          <%= link_to "Home", root_path, class: "btn-link"  %>
            <%# <button class="btn-link focus-tab", id="home-tab", onclick="updateFocus(this)">HOME</button> %>
        </li>
        <li class="<%= is_active?(overview_path)%>">
         <%= link_to "Dashboard", overview_path, class: "btn-link"  %>
          <%# <%= link_to "dashboard" do %>
            <%# <button class="btn-link", id="dashboard-tab", onclick="updateFocus(this)">DASHBOARD</button> %>
          <%# <% end %>
        </li>
        <li class="<%= is_active?(bookmarks_path)%>">
         <%= link_to "Favorites", bookmarks_path, class: "btn-link"  %>
          <%# <%= link_to root_path do %>
            <%# <button class="btn-link", id="lists-tab", onclick="updateFocus(this)">MY LISTS</button> %>
          <%# <% end %>
        </li>
        <li class="<%= is_active?(categories_path)%>">
        <%= link_to "Categories", categories_path, class: "btn-link"  %>
          <%# <%= link_to root_path do %>
            <%# <button class="btn-link", id="favorites-tab", onclick="updateFocus(this)">MY FAVORITES</button> %>
          <%# <% end %>
        </li>
  <%# Hide Searchbar on Homepage %>
  <% unless controller_name == "pages" && action_name = "home" %>
    <li>
      <%# <div data-controller="dropdown">
        <span class="dropmic" data-dropmic="1" role="navigation" data-dropdown-target="dropdowns"     >
          <button data-dropmic-btn class="flag-image" ><img src="https://cdn-icons-png.flaticon.com/512/3013/3013911.png" id="chosen_flag" width="25" height="25"></button>
          <div class="dropmic-menu" aria-hidden="true">
            <li class="dropmic-menu__listItem" role="menuitem">
              <button class="dropmic-menu__listContent" value="ua" onclick="updateLangFlag(this.value)" tabindex="-1"><img id="ua-img" src="https://cdn-icons-png.flaticon.com/512/3013/3013911.png" width="25" height="25"> American English</button>
              <button class="dropmic-menu__listContent" value="ge" onclick="updateLangFlag(this.value)" tabindex="-1"><img id="ge-img" src="https://cdn-icons-png.flaticon.com/512/321/321233.png" width="25" height="25"> German</button>
              <button class="dropmic-menu__listContent" value="fr" onclick="updateLangFlag(this.value)" tabindex="-1"><img id="fr-img" src="https://cdn-icons-png.flaticon.com/512/330/330490.png" width="25" height="25"> French</button>
            </li>
          </div>
        </span>
      </div> %>
      <%= form_tag signs_path, class: "searchbar", id: "searchbar", method: :get, html: { data: {search_signs_target: 'form'}}, autocomplete: "off" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Search"
          %>
        <button type="submit" class="search-button">
          <%= image_tag "search.png", class: "search-image" %>
        </button>
      <% end %>
    </li>
  <% end  %>

        <li class="nav-item dropdown">
          <%= image_tag "user-icon.svg", class: "avatar-bordered dropdown-toggle user-avatar ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "All Signs", signs_path, class: "dropdown-item" %>
            <%= link_to "Create", new_sign_path, class: "dropdown-item" %>
            <%# <%= link_to "Categories", categories_path, class: "dropdown-item" %>
            <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <%# <a class="dropdown-item" data-method="delete" href="/users/sign_out" rel="nofollow">Log out</a> %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>