config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "dashboards#overview", as: "overview"
  get "signs/requests", to: "signs#requests", as: "requests"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :signs
  resources :bookmarks
  resources :categories, only: [ :index, :show ]
  # resources :comments, only: [ :new, :create ] - should be nested inside :signs
  # resources :comments, only: [ :edit, :update, :destroy ]
  # resources :bookmarks, only: [ :index, :destroy ]
  # resources :lists do
  #   resources :bookmarks, only: [ :new, :create ]
  # end

end

app/models/sign.rb
class Sign < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :bookmarks, dependent: :destroy
  validates :title, presence: true
  has_one_attached :video
  enum status: { open: 0, verified: 1 }
  enum language: { german: 0, english: 1, french: 2 , swedish: 3, albanian:4, bulgarian: 5 }

  include PgSearch::Model
  multisearchable against: [:title, :description, :language]

  pg_search_scope :global_search,
                  against: {
                    title: 'A',
                    description: 'B',
                    language: 'C'
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/controllers/signs_controller.rb
class SignsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :policy_scope_signs, only: [ :index, :show, :new, :edit, :update, :destroy ]
  before_action :find_sign, only: [ :show, :edit, :update, :destroy ]

  # For the search function
  def index
    if params.present? && ((params[:language].present?) || (params[:query].present?))
      @items = []
      if params[:language].present?
        @items += Sign.where(language: params[:language])
      end
      if params[:query].present?
        # @items += Sign.where(title: params[:query]).or(Sign.where(description: params[:query]))
        @items += Sign.where("title ILIKE ?", "%#{params[:query]}%").or(Sign.where("description ILIKE ?", "%#{params[:query]}%"))
      end
      @signs = find_results(@items.uniq)
    else
      @signs = find_results(Sign.all)
    end
    @bookmark = Bookmark.new

  end

  def show
    authorize @sign
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  def new
    @sign = Sign.new
    authorize @sign
    @categories = Category.all
  end

  def create
    @sign = Sign.new(sign_params)
    @sign.user = current_user
    authorize @sign
    if @sign.save!
      redirect_to sign_path(@sign)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @sign.update(sign_params)
      redirect_to @sign, notice: "Your amazing sign is edited"
    else
      render :edit
    end
  end

  def destroy
    @sign = Sign.find(params[:id])
    authorize @sign
    @sign.destroy
    redirect_to signs_path, notice: "Oh no! Bye bye to the amazing Sign 👋"
  end

  def requests
    authorize Sign
    # find_requests
    @inquiries = current_user.signs
  end

  private

  def find_sign
    @sign = Sign.find(params[:id])
    authorize @sign
  end

  def sign_params
    params.require(:sign).permit(:language, :title, :description, :video, :category_id)
  end

  def policy_scope_signs
    @signs = policy_scope(Sign)
  end

  def find_results(signs)
    results = []
    signs.each do |sign|
      if sign.video.attached?
        results << sign
      end
    end
    results
  end
end

app/views/signs/edit.html.erb
<!-- app/views/signs/edit.html.erb -->
<div class="container py-5 form-adjust">
  <div>
    <h1 class="font-beta">Edit your Sign</h1>
  </div>

  <%= render "shared/form" %>
</div>

app/views/signs/index.html.erb
<!-- app/views/signs/index.html.erb -->
<section class="container-index">
  <div class="backdrop-index">
    <%# <img src="https://images.unsplash.com/photo-1530569673472-307dc017a82d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80" class="backdrop-index-img" alt="BG"> %>
  </div>
    <% if @signs.count > 1 %>
      <p class="results-count">There are <span class="sign-count"><%= @signs.count %></span> results for your search</p>
    <% else %>
      <p class="results-count"><p class="results-count">There is <span class="sign-count"><%= @signs.count %></span> result for your search</p></p>
    <% end %>
    <%# ********** Signs Container *************  %>
  <div class="signs-container">
    <div class="signs-grid">
      <% @signs.each do |sign| %>
        <% if sign.video.attached? %>
          <div class="sign-card--index">
            <%= link_to sign_path(sign), class: "sign-card-link" do %>
              <h1 class="animated font-gamma">
                <%=sign.title %>
              </h1>
            <% end %>
              <div class="form-bookmark">
                <% if !sign.bookmarks.empty? %>
                    <% if user_signed_in? %>
                      <%= simple_form_for(sign.bookmarks[0], url: bookmark_path(sign.bookmarks[0]), method: :delete, remote: true) do |f| %>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.hidden_field :sign_id, value: sign.id %>
                        <%= image_submit_tag("heart.png", class: 'sign-liked', alt: 'submit') %>
                      <% end %>
                    <% end %>
                <% else %>
                  <% if user_signed_in? %>
                  <%= simple_form_for((@bookmark), remote: true) do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :sign_id, value: sign.id %>
                    <%= image_submit_tag("empty_heart.png", class: 'sign-liked heart-like', alt: 'submit') %>
                  <% end %>
                  <% end %>
                <% end %>
              </div>
              <div class="sign__infos">
                <p class="sign-category text-para--light"><%sign.category.title %></p>
                <p class="sign-description text-para--light"><%=sign.description %></p>
              </div>
              <div class="video-sign-container">
                <%= cl_video_tag(sign.video.key, :controls=>false, :autoplay=>false, :loop=>true, :muted=>true, :width=>220, :height=>150, class:"video")%>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>

app/views/signs/new.html.erb
<%# signup/views/signs/new.html.erb %>
<section class="new-sign">
  <h1 class="font-beta">Upload a new Sign</h1>
  <div class="d-flex">
    <%= simple_form_for(@sign, html: { class: "video_form text-form size-boxes"}) do |f| %>
      <%= f.input :language, collection: ["german", "english", "french", "swedish", "albanian", "bulgarian"]  %>
      <%= f.input :title %>
      <%= f.input :description %>
      <%= f.association :category %>
      <%= f.input :video, as: :file %>
      <%= f.submit "Create Sign", class: "btn-form" %>
    <% end %>
    <div>
      <h2 class="font-gamma">Record your own Sign</h2>
      <button class="create_video_button" id="start">Start</button>
      <button class="create_video_button" id="stop">Stop</button>
      <button class="create_video_button" id="save">Save</button>
      <div>
        <video id="live" height="200" width="300" style="border: 1px solid black" autoplay muted></video>
      </div>
      <%# <div>
        <video id="playback" height="200" width="300" style="border: 1px solid black" controls></video>
      </div> %>
    </div>
  </div>
</section>

app/views/signs/requests.html.erb
<!-- app/views/signs/requests.html.erb -->
<% if inquiry.video.attached? %>
  <% @inquiries.each do |inquiry| %>
    <%= inquiry.title %>
    <%= inquiry.description %>
    <%= inquiry.status %>
      <div class="video-sign-container">
        <%= cl_video_tag(inquiry.video.key, :controls=>false, :autoplay=>false, :loop=>true, :muted=>true, :width=>220, :height=>150, class:"video")%>
      </div>
  <% end %>
<% end %>

app/views/signs/show.html.erb
<!-- app/views/signs/show.html.erb -->
<section class="container-show">
<div class="head-container-show">
    <% if @sign.language == "german"%>
      <%= image_tag "deutschland.png", class: "flag-container flag-image"%>
    <% elsif @sign.language == "english" %>
      <%= image_tag "usa.png", class: "flag-container flag-image" %>
    <% elsif @sign.language == "french" %>
      <%= image_tag "france.png", class: "flag-container flag-image" %>
    <% elsif @sign.language == "swedish" %>
      <%= image_tag "sweden.png", class: "flag-container flag-image"%>
    <% end %>
  <h1 class="font-alpha show__title "><%= @sign.title %></h1>
</div>

    <div class="sign-card--show">
      <div class="tag tag--video">
        <% if @sign.video.attached? %>
          <%= cl_video_tag(@sign.video.key, :controls=>false, :autoplay=>true, :loop=>true, :muted=>true, :width=>480, :height=> 300,class:"video video--show")%>
        <% end %>
      </div>
      <div class="tag tag--description">
        <div class="sign__texts">
          <h3 class="sign__example font-gamma">Description</h3>
          <p class="text-para--medium"><%= @sign.description %></p>
          <h2 class="sign__example font-gamma">Category</h2>
          <p class="text-para--medium"><%= @sign.category.title %></p>
          <div class="sign-buttons sign-buttons-2">
            <% if user_signed_in? && policy(@sign).edit? %>
              <%= link_to "Update", edit_sign_path(@sign), class:"btn create_video_button text-para--medium", id:"save" %>
            <% end %>
            <% if user_signed_in? && policy(@sign).destroy? %>
              <%= link_to "Delete", sign_path(@sign), class:"btn text-para--medium", method: :delete, data: { confirm: "Do you really want to say bye bye?" } %>
            <% end %>
            <% if user_signed_in? %>
            <div class="form-bookmark bookmark-sign">
                <% if !@sign.bookmarks.empty? %>
                    <%= simple_form_for(@sign.bookmarks[0], url: bookmark_path(@sign.bookmarks[0]), method: :delete, remote: true) do |f| %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                      <%= f.hidden_field :sign_id, value: @sign.id %>
                      <%= image_submit_tag("heart.png", class: 'sign-liked', alt: 'submit') %>
                    <% end %>
                <% else %>
                  <%= simple_form_for((@bookmark), remote: true) do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :sign_id, value: @sign.id %>
                    <%= image_submit_tag("empty_heart.png", class: 'sign-liked heart-like', alt: 'submit') %>
                  <% end %>
                <% end %>
             </div>
             <% end %>
          </div>
        </div>
      </div>
      <%# <div class="tag tag--controllers">
        <div class="sign__extras">
        </div>
      </div> %>
    </div>
</section>