config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root to: 'pages#home'
  get "dashboard", to: "dashboards#overview", as: "overview"
  get "signs/requests", to: "signs#requests", as: "requests"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :signs
  resources :bookmarks
  resources :categories, only: [ :index, :show ]
  # resources :comments, only: [ :new, :create ] - should be nested inside :signs
  # resources :comments, only: [ :edit, :update, :destroy ]
  # resources :bookmarks, only: [ :index, :destroy ]
  # resources :lists do
  #   resources :bookmarks, only: [ :new, :create ]
  # end

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_many :signs
  validates :title, presence: true

  include PgSearch::Model
  multisearchable against: [:title]

end

app/controllers/categories_controller.rb
# app/controllers/categories_controller.rb

class CategoriesController < ApplicationController
  before_action :policy_scope_categories, only: [ :index, :show, :new, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      @categories = Category.global_search(params[:query])
    else
      @categories = Category.all
    end
    @bookmark = Bookmark.new
  end

  def show
    @category = Category.find(params[:id])
    @signs = Sign.where(category: @category)
    authorize @category
    @bookmark = Bookmark.new
    authorize @bookmark
  end

  private

  def policy_scope_categories
    @categories = policy_scope(Category)
  end

  def category_params
    params.require(:category).permit(:title)
  end
end

app/views/categories/index.html.erb
<%# app/views/categories/index.html.erb %>
<section class="container-index">
<h2 class="font-alpha">Sign Categories</h2>
  <div class="backdrop-index">
    <%# <img src="https://images.unsplash.com/photo-1530569673472-307dc017a82d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=688&q=80" class="backdrop-index-img" alt="BG"> %>
  </div>
  <div class="categories-container">
    <div class="categories-grid">
      <% @categories.each do |category| %>
          <div class="category-card--index">
            <%= link_to category_path(category), class: "category-card-link font-gamma" do %>
            <h1 class="font-gamma">
              <%=category.title %>
            </h1>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>
</section>

app/views/categories/show.html.erb
<!-- app/views/categories/show.html.erb -->

<section class="container-show">
    <h1 class="font-alpha show__title "><%= @category.title %></h1>
  <div class="signs-container">
    <div class="signs-grid">
      <% @signs.each do |sign| %>
        <% if sign.video.attached? %>
          <div class="sign-card--index">
            <%= link_to sign_path(sign), class: "sign-card-link" do %>
              <h1 class="animated font-gamma">
                <%=sign.title %>
              </h1>
            <% end %>
              <div class="form-bookmark">
                <% if !sign.bookmarks.empty? %>
                    <%= simple_form_for(sign.bookmarks[0], url: bookmark_path(sign.bookmarks[0]), method: :delete) do |f| %>
                      <%= f.hidden_field :user_id, value: current_user.id %>
                      <%= f.hidden_field :sign_id, value: sign.id %>
                      <%= image_submit_tag("heart.png", class: 'sign-liked', alt: 'submit') %>
                    <% end %>
                <% else %>
                  <%= simple_form_for(@bookmark) do |f| %>
                    <%= f.hidden_field :user_id, value: current_user.id %>
                    <%= f.hidden_field :sign_id, value: sign.id %>
                    <%= image_submit_tag("empty_heart.png", class: 'sign-liked heart-like', alt: 'submit') %>
                  <% end %>
                <% end %>
              </div>
              <div class="sign__infos">
                <p class="sign-category text-para--light"><%sign.category.title %></p>
                <p class="sign-description text-para--light"><%=sign.description %></p>
              </div>
              <div class="video-sign-container">
                <%= cl_video_tag(sign.video.key, :controls=>false, :autoplay=>false, :loop=>true, :muted=>true, :width=>220, :height=>150, class:"video")%>
              </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>